# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  repository: opea/chatqna
redis-vector-db:
  enabled: false

# Common fields between data-prep and retriever-usvc must match
# to ensure that RAG works properly
data-prep:
  DATAPREP_BACKEND: "OPENSEARCH"
  OPENSEARCH_HOST: "opensearch-cluster-master"
  OPENSEARCH_PORT: 9200
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: ""
  OPENSEARCH_SSL: true
  INDEX_NAME: "rag_opensearch"
  KEY_INDEX_NAME: "file-keys"
  TIMEOUT_SECONDS: 600
  SEARCH_BATCH_SIZE: 10
retriever-usvc:
  RETRIEVER_BACKEND: "OPENSEARCH"
  OPENSEARCH_HOST: "opensearch-cluster-master"
  OPENSEARCH_PORT: 9200
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: ""
  OPENSEARCH_SSL: true
  OPENSEARCH_INDEX_NAME: "rag_opensearch"

opensearch:
  enabled: true
  persistence:
    enabled: false
  singleNode: true
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: "" # must match value above or data-prep cannot access OpenSearch
