# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

tgi:
  enabled: false
  
vllm:
  enabled: true
  openvino_enabled: true
  image:
    repository: opea/vllm-openvino
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  extraCmdArgs: []

  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3

  CUDA_GRAPHS: "0"
  VLLM_CPU_KVCACHE_SPACE: 50
  VLLM_OPENVINO_KVCACHE_SPACE: 32
  OMPI_MCA_btl_vader_single_copy_mechanism: none

  ov_command: ["/bin/bash"]   
