# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: gmc.opea.io/v1alpha3
kind: GMConnector
metadata:
  labels:
    app.kubernetes.io/name: gmconnector
    app.kubernetes.io/managed-by: kustomize
  name: chatqa
  namespace: gmcsample
spec:
  routerConfig:
    name: router
    nameSpace: gmcsample
    serviceName: router-service
    config:
      no_proxy: ".gmcsample.svc.cluster.local"
      http_proxy: http://child-jf.intel.com:912
      https_proxy: http://child-jf.intel.com:912
  nodes:
    root:
      routerType: Sequence
      steps:
      - name: Embedding
        internalService:
          nameSpace: gmcsample
          serviceName: embedding-service
          config:
            no_proxy: ".gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            tei_endpoint: "http://tei-embedding-service.gmcsample.svc.cluster.local:6006"
            endpoint: /v1/embeddings
      - name: TeiEmbedding
        internalService:
          nameSpace: gmcsample
          serviceName: tei-embedding-service
          config:
            no_proxy: ".gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            gmcTokenSecret: gmc-tokens
            hostPath: /root/GMC/data/tei
            modelId: BAAI/bge-base-en-v1.5
            endpoint: /embed
          isDownstreamService: true
      - name: Retriver
        data: $response
        internalService:
          nameSpace: gmcsample
          serviceName: retriever-redis-server
          config:
            no_proxy: ".gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            RedisUrl: redis://redis-vector-db.gmcsample.svc.cluster.local:6379
            IndexName: rag-redis
            tei_endpoint: "http://tei-embedding-service.gmcsample.svc.cluster.local:6006"
            endpoint: /v1/retrieval
      - name: VectorDB
        internalService:
          nameSpace: gmcsample
          serviceName: redis-vector-db
          isDownstreamService: true
      - name: Reranking
        data: $response
        internalService:
          nameSpace: gmcsample
          serviceName: reranking-service
          config:
            no_proxy: ".gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            tei_reranking_endpoint: http://tei-reranking-service.gmcsample.svc.cluster.local:8808
            gmcTokenSecret: gmc-tokens
            endpoint: /v1/reranking
      - name: TeiReranking
        internalService:
          nameSpace: gmcsample
          serviceName: tei-reranking-service
          config:
            no_proxy: ".gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            gmcTokenSecret: gmc-tokens
            hostPath: /root/GMC/data/rerank
            modelId: BAAI/bge-reranker-large
            endpoint: /rerank
          isDownstreamService: true
      - name: Llm
        data: $response
        internalService:
          nameSpace: gmcsample
          serviceName: llm-service
          config:
            no_proxy: "tgi-service.gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            tgi_endpoint: http://tgi-service.gmcsample.svc.cluster.local:9009
            gmcTokenSecret: gmc-tokens
            endpoint: /v1/chat/completions
      - name: Tgi
        internalService:
          nameSpace: gmcsample
          serviceName: tgi-service
          config:
            no_proxy: "tgi-service.gmcsample.svc.cluster.local"
            http_proxy: http://child-jf.intel.com:912
            https_proxy: http://child-jf.intel.com:912
            gmcTokenSecret: gmc-tokens
            hostPath: /root/GMC/data/tgi
            modelId: Intel/neural-chat-7b-v3-3
            endpoint: /generate
          isDownstreamService: true
