# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

global:
  clusterDomain: "insert-your-cluster-domain-here"

image:
  repository: "insert-your-image-here"  # image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/codegen
  tag: "latest"
  pullPolicy: IfNotPresent

source:
  contextDir: CodeGen
  gitRef: main
  gitUri: "https://github.com/opea-project/GenAIExamples.git"
  type: Git

strategy:
  type: Docker
  dockerfilePath: Dockerfile

replicaCount: 1

port: 7778

service:
  type: ClusterIP
  port: 7778
