# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: qna-config
  namespace: default
data:
  #http_proxy: "http://proxy-dmz.intel.com:911"
  #https_proxy: "http://proxy-dmz.intel.com:912"
  EMBEDDING_MODEL_ID: "BAAI/bge-base-en-v1.5"
  TEI_EMBEDDING_ENDPOINT: "http://tei-embedding-svc.default.svc.cluster.local:6006"
  REDIS_URL: "redis://redis-vector-db.default.svc.cluster.local:6379"
  INDEX_NAME: "rag-redis"
  RERANK_MODEL_ID: "BAAI/bge-reranker-large"
  TEI_RERANKING_ENDPOINT: "http://tei-reranking-svc.default.svc.cluster.local:8808"
  HUGGINGFACEHUB_API_TOKEN: {your_huggingfacehub_api_token}
  # ${HUGGINGFACEHUB_API_TOKEN}
  LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
  TGI_LLM_ENDPOINT: "http://tgi-svc.default.svc.cluster.local:9009"
  MEGA_SERVICE_HOST_IP: 172.16.3.15
  CHAT_BASE_URL: "http://172.16.3.15:30888/v1/chatqna"
