# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for vllm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: opea/llm-vllm-hpu
  tag: "1.0"

VLLM_CPU_KVCACHE_SPACE: "40"

# Workaround for current HPU image with start command /bin/bash
# extraCmdArgs: ["--enforce-eager","--tensor-parallel-size","1","--block-size","128","--max-num-seqs","256","--max-seq_len-to-capture","2048"]
extraCmdArgs: ["/bin/bash","-c","python3 -m vllm.entrypoints.openai.api_server --enforce-eager --model Intel/neural-chat-7b-v3-3 --tensor-parallel-size 1 --host 0.0.0.0 --port 2080 --download-dir /data --block-size 128 --max-num-seqs 256 --max-seq_len-to-capture 2048"]
resources:
  limits:
    habana.ai/gaudi: 1
