# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codegen.fullname" . }}
  labels:
    {{- include "codegen.labels" . | nindent 4 }}
    app: {{ include "codegen.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "codegen.selectorLabels" . | nindent 6 }}
      app: {{ include "codegen.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "codegen.selectorLabels" . | nindent 8 }}
        app: {{ include "codegen.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "codegen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: LLM_SERVICE_HOST_IP
              {{- if .Values.externalLLM.enabled }}
              value: {{ .Values.externalLLM.LLM_SERVER_HOST }}
              {{- else }}
              value: {{ include "llm-uservice.fullname" (index .Subcharts "llm-uservice") | quote }}
              {{- end }}
            - name: LLM_SERVICE_PORT
              {{- if .Values.externalLLM.enabled }}
              value: {{ .Values.externalLLM.LLM_SERVER_PORT | default "80" | quote }}
              {{- else }}
              value: {{ index .Values "llm-uservice" "service" "port" | quote }}
              {{- end }}
            {{- if .Values.externalLLM.enabled }}
            - name: LLM_MODEL_ID
              value: {{ .Values.externalLLM.LLM_MODEL_ID }}
            - name: OPENAI_API_KEY
              value: {{ .Values.externalLLM.OPENAI_API_KEY }}
            {{- end }}
            {{- if index .Values "retriever-usvc" "enabled" }}
            - name: RETRIEVAL_SERVICE_HOST_IP
              value: {{ include "retriever-usvc.fullname" (index .Subcharts "retriever-usvc") | quote }}
            - name: REDIS_RETRIEVER_PORT
              value: {{ index .Values "retriever-usvc" "service" "port" | quote }}
            {{- end }}
            {{- if index .Values "embedding-usvc" "enabled" }}
            - name: TEI_EMBEDDING_HOST_IP
              value: {{ include "embedding-usvc.fullname" (index .Subcharts "embedding-usvc") | quote }}
            - name: EMBEDDER_PORT
              value: {{ index .Values "embedding-usvc" "service" "port" | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          ports:
            - name: codegen
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.evenly_distributed }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "codegen.selectorLabels" . | nindent 14 }}
              app: {{ include "codegen.fullname" . }}
      {{- end }}
