# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  repository: opea/llm-faqgen
  tag: "1.3"

LLM_MODEL_ID: meta-llama/Meta-Llama-3-8B-Instruct

tgi:
  LLM_MODEL_ID: meta-llama/Meta-Llama-3-8B-Instruct
