# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  repository: opea/llm-docsum
  tag: "latest"

DOCSUM_BACKEND: "vLLM"
LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
MAX_INPUT_TOKENS: 2048
MAX_TOTAL_TOKENS: 4096


tgi:
  enabled: false
vllm:
  enabled: true
  image:
    repository: opea/vllm-gaudi
    tag: "latest"
  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
  OMPI_MCA_btl_vader_single_copy_mechanism: none
  NUM_CARDS: 1
  extraCmdArgs: ["--block-size", "128", "--max-num-seqs", "256", "--max-seq_len-to-capture", "2048"]
  resources:
    limits:
      habana.ai/gaudi: 1
