# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retriever-usvc.fullname" . }}-config
  labels:
    {{- include "retriever-usvc.labels" . | nindent 4 }}
data:
  {{- if .Values.TEI_EMBEDDING_ENDPOINT }}
  TEI_EMBEDDING_ENDPOINT: {{ tpl .Values.TEI_EMBEDDING_ENDPOINT . | quote }}
  {{- else if not .Values.LOCAL_EMBEDDING_MODEL }}
  TEI_EMBEDDING_ENDPOINT: "http://{{ .Release.Name }}-tei"
  {{- end }}
  {{- if eq "REDIS" .Values.RETRIEVER_BACKEND }}
  RETRIEVER_COMPONENT_NAME: "OPEA_RETRIEVER_REDIS"
  {{- if .Values.REDIS_HOST }}
  REDIS_HOST: {{ tpl .Values.REDIS_HOST . | quote}}
  {{- else }}
  REDIS_HOST: "{{ .Release.Name }}-redis-vector-db"
  {{- end }}
  REDIS_PORT: {{ .Values.REDIS_PORT | quote }}
  REDIS_SSL: {{ .Values.REDIS_SSL | quote }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | quote }}
  REDIS_USERNAME: {{ .Values.REDIS_USERNAME | quote }}
  INDEX_NAME: {{ .Values.INDEX_NAME | quote }}
  EMBED_MODEL: {{ .Values.LOCAL_EMBEDDING_MODEL | quote }}
  {{- else if eq "MILVUS" .Values.RETRIEVER_BACKEND }}
  RETRIEVER_COMPONENT_NAME: "OPEA_RETRIEVER_MILVUS"
  {{- if .Values.MILVUS_HOST }}
  MILVUS_HOST: {{ tpl .Values.MILVUS_HOST . | quote }}
  {{- else }}
  MILVUS_HOST: "{{ .Release.Name }}-milvus"
  {{- end }}
  MILVUS_PORT: {{ .Values.MILVUS_PORT | quote }}
  COLLECTION_NAME: {{ .Values.COLLECTION_NAME | quote }}
  LOCAL_EMBEDDING_MODEL: {{ .Values.LOCAL_EMBEDDING_MODEL | quote }}
  {{- else if eq "QDRANT" .Values.RETRIEVER_BACKEND }}
  RETRIEVER_COMPONENT_NAME: "OPEA_RETRIEVER_QDRANT"
  {{- if .Values.QDRANT_HOST }}
  QDRANT_HOST: {{ tpl .Values.QDRANT_HOST . | quote }}
  {{- else }}
  QDRANT_HOST: "{{ .Release.Name }}-qdrant"
  {{- end }}
  QDRANT_PORT: {{ .Values.QDRANT_PORT | quote }}
  QDRANT_EMBED_DIMENSION: {{ .Values.QDRANT_EMBED_DIMENSION | quote }}
  QDRANT_INDEX_NAME: {{ .Values.QDRANT_INDEX_NAME | quote }}
  {{- else }}
  {{- cat "Invalid RETRIEVER_BACKEND:" .Values.RETRIEVER_BACKEND | fail }}
  {{- end }}
  {{- if .Values.global.HF_ENDPOINT }}
  HF_ENDPOINT: {{ .Values.global.HF_ENDPOINT | quote}}
  {{- end }}
  EASYOCR_MODULE_PATH: "/tmp/.EasyOCR"
  http_proxy: {{ .Values.global.http_proxy | quote }}
  https_proxy: {{ .Values.global.https_proxy | quote }}
  {{- if and (and (not .Values.MILVUS_HOST ) (not .Values.REDIS_HOST)) (and (not .Values.TEI_EMBEDDING_ENDPOINT) (or .Values.global.http_proxy .Values.global.https_proxy)) }}
  no_proxy: "{{ .Release.Name }}-tei,{{ .Release.Name }}-redis-vector-db,{{ .Release.Name }}-milvus,{{ .Values.global.no_proxy }}"
  {{- else }}
  no_proxy: {{ tpl .Values.global.no_proxy . | quote }}
  {{- end }}
  HF_HOME: "/tmp/.cache/huggingface"
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.global.HUGGINGFACEHUB_API_TOKEN | quote}}
  LOGFLAG: {{ .Values.LOGFLAG | quote }}
  NUMBA_CACHE_DIR: "/tmp/numba/cache"
  MPLCONFIGDIR: "/tmp/matplotlib"
  HAYSTACK_TELEMETRY_ENABLED: "False"
