---
# Source: whisper/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: whisper-config
  labels:
    helm.sh/chart: whisper-0.8.0
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  EASYOCR_MODULE_PATH: "/tmp/.EasyOCR"
  ASR_MODEL_PATH: "openai/whisper-small"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  HF_HOME: "/tmp/.cache/huggingface"
  HUGGINGFACE_HUB_CACHE: "/data"
---
# Source: whisper/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: whisper
  labels:
    helm.sh/chart: whisper-0.8.0
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7066
      targetPort: 7066
      protocol: TCP
      name: whisper
  selector:
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
---
# Source: whisper/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  labels:
    helm.sh/chart: whisper-0.8.0
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whisper
      app.kubernetes.io/instance: whisper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whisper
        app.kubernetes.io/instance: whisper
    spec:
      securityContext:
        {}
      containers:
        - name: whisper
          envFrom:
            - configMapRef:
                name: whisper-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/whisper-gaudi:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: whisper
              containerPort: 7066
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /tmp
              name: tmp
          resources:
            {}
      volumes:
        - name: model-volume
          hostPath:
            path: /mnt/opea-models
            type: Directory
        - name: tmp
          emptyDir: {}
