# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for codegen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hfToken: "insert-your-huggingface-token-here"
# tgiEndpoint: "http://automaticallydetected"

image:
  repository: intel/gen-ai-examples
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "copilot"

service:
  type: ClusterIP
  port: 80

# To override values in subchart tgi
tgi:
  hftgi:
    modelId: m-a-p/OpenCodeInterpreter-DS-6.7B
    # modelId: /data/OpenCodeInterpreter-DS-6.7B
    port: 80
    volume: /mnt

  image:
    repository: ghcr.io/huggingface/text-generation-inference
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.4"
