apiVersion: v1
data:
  default.conf: |+
    # Copyright (C) 2024 Intel Corporation
    # SPDX-License-Identifier: Apache-2.0


    server {
        listen       80;
        listen  [::]:80;

        location /home {
            alias  /usr/share/nginx/html/index.html;
        }

        location / {
            proxy_pass http://{{ include "ui.fullname" (index .Subcharts "videoqna-ui") }}:{{ index .Values "videoqna-ui" "service" "port" }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v1/videoqna {
            proxy_pass http://{{ include "videoqna.fullname" . }}:{{ .Values.service.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v1/dataprep {
            proxy_pass http://{{ include "data-prep.fullname" (index .Subcharts "data-prep") }}:{{ index .Values "data-prep" "service" "port" }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v1/dataprep/get_file {
            proxy_pass http://{{ include "data-prep.fullname" (index .Subcharts "data-prep") }}:{{ index .Values "data-prep" "service" "port" }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v1/dataprep/delete_file {
            proxy_pass http://{{ include "data-prep.fullname" (index .Subcharts "data-prep") }}:{{ index .Values "data-prep" "service" "port" }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

kind: ConfigMap
metadata:
  name: {{ include "videoqna.fullname" . }}-nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videoqna.fullname" . }}-nginx
  labels:
    {{- include "videoqna.labels" . | nindent 4 }}
    app: {{ include "videoqna.fullname" . }}-nginx
spec:
  selector:
    matchLabels:
      {{- include "videoqna.selectorLabels" . | nindent 6 }}
      app: {{ include "videoqna.fullname" . }}-nginx
  template:
    metadata:
      labels:
        {{- include "videoqna.selectorLabels" . | nindent 8 }}
        app: {{ include "videoqna.fullname" . }}-nginx
    spec:
      containers:
      - image: nginx:1.27.1
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config-volume
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "videoqna.fullname" . }}-nginx-config
        name: nginx-config-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "videoqna.fullname" . }}-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "videoqna.selectorLabels" . | nindent 4 }}
    app: {{ include "videoqna.fullname" . }}-nginx
  type: NodePort
