# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tei.fullname" . }}-config
  labels:
    {{- include "tei.labels" . | nindent 4 }}
data:
  MODEL_ID: {{ .Values.EMBEDDING_MODEL_ID | quote }}
  PORT: {{ .Values.port | quote }}
  http_proxy: {{ .Values.global.http_proxy | quote }}
  https_proxy: {{ .Values.global.https_proxy | quote }}
  no_proxy: {{ .Values.global.no_proxy | quote }}
  NUMBA_CACHE_DIR: "/tmp"
  TRANSFORMERS_CACHE: "/tmp/transformers_cache"
  HF_HOME: "/tmp/.cache/huggingface"
  MAX_WARMUP_SEQUENCE_LENGTH: "512"
