# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-vllm-uservice.fullname" . }}-config
  labels:
    {{- include "llm-vllm-uservice.labels" . | nindent 4 }}
data:
  {{- if .Values.vLLM_ENDPOINT }}
  vLLM_ENDPOINT: {{ .Values.vLLM_ENDPOINT | quote}}
  {{- else }}
  vLLM_ENDPOINT: "http://{{ .Release.Name }}-vllm-openvino"
  {{- end }}
  LLM_MODEL: {{ .Values.LLM_MODEL_ID | quote }}
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.global.HUGGINGFACEHUB_API_TOKEN | quote}}
  HF_HOME: "/tmp/.cache/huggingface"
  {{- if .Values.global.HF_ENDPOINT }}
  HF_ENDPOINT: {{ .Values.global.HF_ENDPOINT | quote}}
  {{- end }}
  http_proxy: {{ .Values.global.http_proxy | quote }}
  https_proxy: {{ .Values.global.https_proxy | quote }}
  {{- if and (not .Values.vLLM_ENDPOINT) (or .Values.global.http_proxy .Values.global.https_proxy) }}
  no_proxy: "{{ .Release.Name }}-vllm-openvino,{{ .Values.global.no_proxy }}"
  {{- else }}
  no_proxy: "{{ .Values.global.no_proxy }}, vllm-openvino"
  {{- end }}
  LANGCHAIN_TRACING_V2: {{ .Values.global.LANGCHAIN_TRACING_V2 | quote }}
  LANGCHAIN_API_KEY: {{ .Values.global.LANGCHAIN_API_KEY }}
  LANGCHAIN_PROJECT: "opea-llm-uservice"
  HF_HUB_DISABLE_PROGRESS_BARS: {{ .Values.HF_HUB_DISABLE_PROGRESS_BARS | quote }}
  HF_HUB_ENABLE_HF_TRANSFER: {{ .Values.HF_HUB_ENABLE_HF_TRANSFER | quote }}
