# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audioqna.fullname" . }}
  labels:
    {{- include "audioqna.labels" . | nindent 4 }}
    app: {{ include "audioqna.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "audioqna.selectorLabels" . | nindent 6 }}
      app: {{ include "audioqna.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "audioqna.selectorLabels" . | nindent 8 }}
        app: {{ include "audioqna.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "audioqna.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: LLM_SERVER_HOST_IP
              {{- if .Values.tgi.enabled }}
              value: {{ include "tgi.fullname" (index .Subcharts "tgi") }}
              {{- else if .Values.vllm.enabled }}
              value: {{ include "vllm.fullname" (index .Subcharts "vllm") }}
              {{- end }}
            - name: LLM_SERVER_PORT
              value: "80"
            - name: LLM_MODEL_ID
              {{- if .Values.tgi.enabled }}
              value: {{ .Values.tgi.LLM_MODEL_ID | quote }}
              {{- else if .Values.vllm.enabled }}
              value: {{ .Values.vllm.LLM_MODEL_ID | quote }}
              {{- end }}
            - name: WHISPER_SERVER_HOST_IP
              value: {{ include "whisper.fullname" (index .Subcharts "whisper") }}
            - name: WHISPER_SERVER_PORT
              value: {{ index .Values "whisper" "service" "port" | quote }}
            {{- if .Values.speecht5.enabled }}
            - name: SPEECHT5_SERVER_HOST_IP
              value: {{ include "speecht5.fullname" (index .Subcharts "speecht5") }}
            - name: SPEECHT5_SERVER_PORT
              value: {{ index .Values "speecht5" "service" "port" | quote }}
            {{- else if index .Values "gpt-sovits" "enabled" }}
            - name: GPT_SOVITS_SERVER_HOST_IP
              value: {{ include "gpt-sovits.fullname" (index .Subcharts "gpt-sovits") }}
            - name: GPT_SOVITS_SERVER_PORT
              value: {{ index .Values "gpt-sovits" "service" "port" | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          ports:
            - name: audioqna
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.evenly_distributed }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "audioqna.selectorLabels" . | nindent 14 }}
              app: {{ include "audioqna.fullname" . }}
      {{- end }}
