---
# Source: agent/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    helm.sh/chart: agent-1.2.0
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  tools: "/home/user/tools/supervisor_agent_tools.yaml"
  llm_endpoint_url: "http://agent-vllm"
  #
  model: "meta-llama/Meta-Llama-3.1-70B-Instruct"
  stream: "false"
  temperature: "0.01"
  RETRIEVAL_TOOL_URL: "http://agent-docretriever:8889/v1/retrievaltool"
  CRAG_SERVER: "http://agent-crag:8080"
  WORKER_AGENT_URL: "http://agent-ragagent:9095/v1/chat/completions"
  SQL_AGENT_URL: "http://agent-sqlagent:9096/v1/chat/completions"
  require_human_feedback: "false"
  recursion_limit: "10"
  llm_engine: "vllm"
  strategy: "react_llama"
  use_hints: 
  max_new_tokens: "4096"
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
  HF_HOME: "/tmp/.cache/huggingface"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  LOGFLAG: ""
---
# Source: agent/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: agent
  labels:
    helm.sh/chart: agent-1.2.0
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: agent
  selector:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
---
# Source: agent/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    helm.sh/chart: agent-1.2.0
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
      app.kubernetes.io/instance: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent
        app.kubernetes.io/instance: agent
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: agent
          envFrom:
            - configMapRef:
                name: agent-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/agent:1.2"
          ports:
            - name: agent
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user/tools
              name: tool
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: agent
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: agent
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: agent
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: tool
          hostPath:
            path: /mnt/tools
            type: Directory
        - name: tmp
          emptyDir: {}
---
# Source: agent/templates/serviceaccount.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: agent/templates/servicemonitor.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
