---
# Source: asr/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: asr-config
  labels:
    helm.sh/chart: asr-1.0.0
    app.kubernetes.io/name: asr
    app.kubernetes.io/instance: asr
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  ASR_ENDPOINT: "http://asr-whisper:7066"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
---
# Source: asr/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: asr
  labels:
    helm.sh/chart: asr-1.0.0
    app.kubernetes.io/name: asr
    app.kubernetes.io/instance: asr
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9099
      targetPort: 9099
      protocol: TCP
      name: asr
  selector:
    app.kubernetes.io/name: asr
    app.kubernetes.io/instance: asr
---
# Source: asr/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr
  labels:
    helm.sh/chart: asr-1.0.0
    app.kubernetes.io/name: asr
    app.kubernetes.io/instance: asr
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asr
      app.kubernetes.io/instance: asr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: asr
        app.kubernetes.io/instance: asr
    spec:
      securityContext:
        {}
      containers:
        - name: asr
          envFrom:
            - configMapRef:
                name: asr-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/asr:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: asr
              containerPort: 9099
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: asr
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: asr
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: asr
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {}
      volumes:
        - name: tmp
          emptyDir: {}
