---
# Source: guardrails-usvc/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: guardrails-usvc-config
  labels:
    helm.sh/chart: guardrails-usvc-1.0.0
    app.kubernetes.io/name: guardrails-usvc
    app.kubernetes.io/instance: guardrails-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  SAFETY_GUARD_ENDPOINT: "http://guardrails-usvc-tgi"
  SAFETY_GUARD_MODEL_ID: "meta-llama/Meta-Llama-Guard-2-8B"
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
  HF_HOME: "/tmp/.cache/huggingface"
  LOGFLAG: ""
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
---
# Source: guardrails-usvc/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: guardrails-usvc
  labels:
    helm.sh/chart: guardrails-usvc-1.0.0
    app.kubernetes.io/name: guardrails-usvc
    app.kubernetes.io/instance: guardrails-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: guardrails-usvc
  selector:
    app.kubernetes.io/name: guardrails-usvc
    app.kubernetes.io/instance: guardrails-usvc
---
# Source: guardrails-usvc/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrails-usvc
  labels:
    helm.sh/chart: guardrails-usvc-1.0.0
    app.kubernetes.io/name: guardrails-usvc
    app.kubernetes.io/instance: guardrails-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guardrails-usvc
      app.kubernetes.io/instance: guardrails-usvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guardrails-usvc
        app.kubernetes.io/instance: guardrails-usvc
    spec:
      securityContext:
        {}
      containers:
        - name: guardrails-usvc
          envFrom:
            - configMapRef:
                name: guardrails-usvc-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/guardrails-tgi:1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: guardrails-usvc
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: guardrails-usvc
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: guardrails-usvc
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: guardrails-usvc
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {}
      volumes:
        - name: tmp
          emptyDir: {}
