---
# Source: lvm-uservice/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: lvm-uservice-config
  labels:
    helm.sh/chart: lvm-uservice-1.1.0
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  LVM_ENDPOINT: "http://lvm-uservice-tgi"
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
  HF_HOME: "/tmp/.cache/huggingface"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  LOGFLAG: ""
---
# Source: lvm-uservice/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: lvm-uservice
  labels:
    helm.sh/chart: lvm-uservice-1.1.0
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9399
      targetPort: 9399
      protocol: TCP
      name: lvm-uservice
  selector:
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
---
# Source: lvm-uservice/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvm-uservice
  labels:
    helm.sh/chart: lvm-uservice-1.1.0
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lvm-uservice
      app.kubernetes.io/instance: lvm-uservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lvm-uservice
        app.kubernetes.io/instance: lvm-uservice
    spec:
      securityContext:
        {}
      containers:
        - name: lvm-uservice
          envFrom:
            - configMapRef:
                name: lvm-uservice-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/lvm-tgi:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: lvm-uservice
              containerPort: 9399
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: lvm-uservice
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: lvm-uservice
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: lvm-uservice
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {}
      volumes:
        - name: tmp
          emptyDir: {}
---
# Source: lvm-uservice/templates/servicemonitor.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
