---
# Source: lvm-uservice/charts/lvm-serve/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: lvm-uservice-lvm-serve-config
  labels:
    helm.sh/chart: lvm-serve-1.2.0
    app.kubernetes.io/name: lvm-serve
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Helm
data:
  LVM_MODEL_ID: "llava-hf/llava-1.5-7b-hf"
  HF_TOKEN: "insert-your-huggingface-token-here"
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  LOGFLAG: ""
  HF_HOME: "/tmp/.cache/huggingface"
  HF_HUB_CACHE: "/data"
  HABANA_LOGS: "/tmp/habana_logs"
---
# Source: lvm-uservice/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: lvm-uservice-config
  labels:
    helm.sh/chart: lvm-uservice-1.2.0
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  LVM_ENDPOINT: "http://lvm-uservice-lvm-serve"
  LVM_COMPONENT_NAME: "OPEA_LLAVA_LVM"
  HF_TOKEN: "insert-your-huggingface-token-here"
  HF_HOME: "/tmp/.cache/huggingface"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  LOGFLAG: ""
---
# Source: lvm-uservice/charts/lvm-serve/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: lvm-uservice-lvm-serve
  labels:
    helm.sh/chart: lvm-serve-1.2.0
    app.kubernetes.io/name: lvm-serve
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: lvm-serve
      protocol: TCP
      name: lvm-serve
  selector:
    app.kubernetes.io/name: lvm-serve
    app.kubernetes.io/instance: lvm-uservice
---
# Source: lvm-uservice/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: lvm-uservice
  labels:
    helm.sh/chart: lvm-uservice-1.2.0
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9399
      targetPort: 9399
      protocol: TCP
      name: lvm-uservice
  selector:
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
---
# Source: lvm-uservice/charts/lvm-serve/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvm-uservice-lvm-serve
  labels:
    helm.sh/chart: lvm-serve-1.2.0
    app.kubernetes.io/name: lvm-serve
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lvm-serve
      app.kubernetes.io/instance: lvm-uservice
  template:
    metadata:
      labels:
        helm.sh/chart: lvm-serve-1.2.0
        app.kubernetes.io/name: lvm-serve
        app.kubernetes.io/instance: lvm-uservice
        app.kubernetes.io/version: "1.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        {}
      initContainers:
        - name: model-downloader
          envFrom:
            - configMapRef:
                name: lvm-uservice-lvm-serve-config
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsGroup: 0
            capabilities:
              drop:
              - ALL
              add:
              - DAC_OVERRIDE
              # To be able to make data model directory group writable for
              # previously downloaded model by old versions of helm chart
              - FOWNER
            seccompProfile:
              type: RuntimeDefault
          image: huggingface/downloader:0.17.3
          command: ['sh', '-ec']
          args:
            - |
              echo "Huggingface log in ...";
              huggingface-cli login --token $(HF_TOKEN);
              echo "Download model llava-hf/llava-1.5-7b-hf ... ";
              huggingface-cli download --cache-dir /data "llava-hf/llava-1.5-7b-hf";
              echo "Change model files mode ...";
              chmod -R g+w /data/models--llava-hf--llava-1.5-7b-hf
              # NOTE: Buggy logout command;
              # huggingface-cli logout;
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /tmp
              name: tmp
      containers:
        - name: lvm-serve
          envFrom:
            - configMapRef:
                name: lvm-uservice-lvm-serve-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/lvm-llava:1.2"
          args:
            - "--model_name_or_path"
            - "llava-hf/llava-1.5-7b-hf"
          ports:
            - name: lvm-serve
              containerPort: 8399
              protocol: TCP
          readinessProbe:
            httpGet:
              path: health
              port: lvm-serve
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: health
              port: lvm-serve
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: model-volume
          hostPath:
            path: /mnt/opea-models
            type: Directory
        - name: tmp
          emptyDir: {}
      # extra time to finish processing buffered requests on CPU before pod is forcibly terminated
      terminationGracePeriodSeconds: 120
---
# Source: lvm-uservice/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvm-uservice
  labels:
    helm.sh/chart: lvm-uservice-1.2.0
    app.kubernetes.io/name: lvm-uservice
    app.kubernetes.io/instance: lvm-uservice
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lvm-uservice
      app.kubernetes.io/instance: lvm-uservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lvm-uservice
        app.kubernetes.io/instance: lvm-uservice
    spec:
      serviceAccountName: default
      securityContext:
        {}
      initContainers:
        - name: wait-for-lvm
          envFrom:
            - configMapRef:
                name: lvm-uservice-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              proto=$(echo ${LVM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\1/p');
              host=$(echo ${LVM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\2/p');
              port=$(echo ${LVM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\3/p');
              if [ -z "$port" ]; then
                  port=80;
                  [[ "$proto" = "https" ]] && port=443;
              fi;
              wait_timeout=1;
              total_timeout=60;
              j=0;
              while ! nc -w ${wait_timeout} -z ${host} ${port}; do
                j=$((j+wait_timeout));
                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${host}:${port} is NOT reachable in $j seconds!" && exit 1;
                j=$((j+2)); sleep 2;
              done;
              echo "${host}:${port} is reachable within $j seconds.";
      containers:
        - name: lvm-uservice
          envFrom:
            - configMapRef:
                name: lvm-uservice-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/lvm:1.2"
          ports:
            - name: lvm-uservice
              containerPort: 9399
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: lvm-uservice
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: lvm-uservice
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: tmp
          emptyDir: {}
---
# Source: lvm-uservice/charts/lvm-serve/templates/horizontal-pod-autoscaler.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: lvm-uservice/charts/lvm-serve/templates/serviceaccount.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: lvm-uservice/charts/lvm-serve/templates/servicemonitor.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
# Source: lvm-uservice/templates/serviceaccount.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: lvm-uservice/templates/servicemonitor.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
