---
# Source: prompt-usvc/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: prompt-usvc-config
  labels:
    helm.sh/chart: prompt-usvc-1.2.0
    app.kubernetes.io/name: prompt-usvc
    app.kubernetes.io/instance: prompt-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  MONGO_HOST: "prompt-usvc-mongodb"
  MONGO_PORT: "27017"
  DB_NAME: "OPEA"
  COLLECTION_NAME: "Prompt"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  LOGFLAG: ""
---
# Source: prompt-usvc/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: prompt-usvc
  labels:
    helm.sh/chart: prompt-usvc-1.2.0
    app.kubernetes.io/name: prompt-usvc
    app.kubernetes.io/instance: prompt-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6018
      targetPort: 6018
      protocol: TCP
      name: port
  selector:
    app.kubernetes.io/name: prompt-usvc
    app.kubernetes.io/instance: prompt-usvc
---
# Source: prompt-usvc/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prompt-usvc
  labels:
    helm.sh/chart: prompt-usvc-1.2.0
    app.kubernetes.io/name: prompt-usvc
    app.kubernetes.io/instance: prompt-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prompt-usvc
      app.kubernetes.io/instance: prompt-usvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prompt-usvc
        app.kubernetes.io/instance: prompt-usvc
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: prompt-usvc
          envFrom:
            - configMapRef:
                name: prompt-usvc-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/promptregistry-mongo-server:1.2"
          ports:
            - name: port
              containerPort: 6018
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: port
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: port
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: port
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: tmp
          emptyDir: {}
---
# Source: prompt-usvc/templates/serviceaccount.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
