---
# Source: retriever-usvc/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: retriever-usvc-config
  labels:
    helm.sh/chart: retriever-usvc-1.2.0
    app.kubernetes.io/name: retriever-usvc
    app.kubernetes.io/instance: retriever-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
data:
  TEI_EMBEDDING_ENDPOINT: "http://retriever-usvc-tei"
  RETRIEVER_COMPONENT_NAME: "OPEA_RETRIEVER_REDIS"
  REDIS_HOST: "retriever-usvc-redis-vector-db"
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  REDIS_PASSWORD: ""
  REDIS_USERNAME: ""
  INDEX_NAME: "rag_redis"
  EMBED_MODEL: ""
  EASYOCR_MODULE_PATH: "/tmp/.EasyOCR"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  HF_HOME: "/tmp/.cache/huggingface"
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
  LOGFLAG: ""
---
# Source: retriever-usvc/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: retriever-usvc
  labels:
    helm.sh/chart: retriever-usvc-1.2.0
    app.kubernetes.io/name: retriever-usvc
    app.kubernetes.io/instance: retriever-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: retriever-usvc
  selector:
    app.kubernetes.io/name: retriever-usvc
    app.kubernetes.io/instance: retriever-usvc
---
# Source: retriever-usvc/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever-usvc
  labels:
    helm.sh/chart: retriever-usvc-1.2.0
    app.kubernetes.io/name: retriever-usvc
    app.kubernetes.io/instance: retriever-usvc
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retriever-usvc
      app.kubernetes.io/instance: retriever-usvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retriever-usvc
        app.kubernetes.io/instance: retriever-usvc
    spec:
      serviceAccountName: default
      securityContext:
        {}
      initContainers:
        - name: wait-for-db
          envFrom:
            - configMapRef:
                name: retriever-usvc-config
            - configMapRef:
                name: extra-env-config
                optional: true
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              TESTHOST=$(REDIS_HOST);
              TESTPORT=$(REDIS_PORT);
              wait_timeout=1;
              total_timeout=60;
              j=0;
              while ! nc -w ${wait_timeout} -z ${TESTHOST} ${TESTPORT}; do
                j=$((j+wait_timeout));
                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${TESTHOST}:${TESTPORT} is NOT reachable in $j seconds!" && exit 1;
                j=$((j+2)); sleep 2;
              done;
              echo "${TESTHOST}:${TESTPORT} is reachable within $j seconds.";
      containers:
        - name: retriever-usvc
          envFrom:
            - configMapRef:
                name: retriever-usvc-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/retriever:1.2"
          ports:
            - name: retriever-usvc
              containerPort: 7000
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: retriever-usvc
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: retriever-usvc
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: tmp
          emptyDir: {}
---
# Source: retriever-usvc/templates/serviceaccount.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: retriever-usvc/templates/servicemonitor.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
