---
# Source: teirerank/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: teirerank-config
  labels:
    helm.sh/chart: teirerank-1.2.0
    app.kubernetes.io/name: teirerank
    app.kubernetes.io/instance: teirerank
    app.kubernetes.io/version: "cpu-1.5"
    app.kubernetes.io/managed-by: Helm
data:
  MODEL_ID: "BAAI/bge-reranker-base"
  PORT: "2082"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  NUMBA_CACHE_DIR: "/tmp"
  TRANSFORMERS_CACHE: "/tmp/transformers_cache"
  HF_HOME: "/tmp/.cache/huggingface"
  HF_HUB_DISABLE_PROGRESS_BARS: "1"
  HF_HUB_ENABLE_HF_TRANSFER: "0"
  # More options for HPU
  HF_TOKEN: "insert-your-huggingface-token-here"
---
# Source: teirerank/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: teirerank
  labels:
    helm.sh/chart: teirerank-1.2.0
    app.kubernetes.io/name: teirerank
    app.kubernetes.io/instance: teirerank
    app.kubernetes.io/version: "cpu-1.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 2082
      protocol: TCP
      name: teirerank
  selector:
    app.kubernetes.io/name: teirerank
    app.kubernetes.io/instance: teirerank
---
# Source: teirerank/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teirerank
  labels:
    helm.sh/chart: teirerank-1.2.0
    app.kubernetes.io/name: teirerank
    app.kubernetes.io/instance: teirerank
    app.kubernetes.io/version: "cpu-1.5"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: teirerank
      app.kubernetes.io/instance: teirerank
  template:
    metadata:
      labels:
        app.kubernetes.io/name: teirerank
        app.kubernetes.io/instance: teirerank
    spec:
      serviceAccountName: default
      securityContext:
        {}
      initContainers:
        - name: model-downloader
          envFrom:
            - configMapRef:
                name: teirerank-config
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsGroup: 0
            capabilities:
              drop:
              - ALL
              add:
              - DAC_OVERRIDE
              # To be able to make data model directory group writable for
              # previously downloaded model by old versions of helm chart
              - FOWNER
            seccompProfile:
              type: RuntimeDefault
          image: huggingface/downloader:0.17.3
          command: ['sh', '-ec']
          args:
            - |
              echo "Huggingface log in ...";
              huggingface-cli login --token $(HF_TOKEN);
              echo "Download model BAAI/bge-reranker-base ... ";
              huggingface-cli download --cache-dir /data "BAAI/bge-reranker-base";
              echo "Change model files mode ...";
              chmod -R g+w /data/models--BAAI--bge-reranker-base;
              # NOTE: Buggy logout command;
              # huggingface-cli logout;
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /tmp
              name: tmp
      containers:
        - name: teirerank
          envFrom:
            - configMapRef:
                name: teirerank-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            {}
          image: "ghcr.io/huggingface/text-embeddings-inference:cpu-1.5"
          args:
            - "--auto-truncate"
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /dev/shm
              name: shm
            - mountPath: /tmp
              name: tmp
          ports:
            - name: http
              containerPort: 2082
              protocol: TCP
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 8
            periodSeconds: 8
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 8
            periodSeconds: 8
            timeoutSeconds: 4
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: model-volume
          hostPath:
            path: /mnt/opea-models
            type: Directory
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir: {}
      # extra time to finish processing buffered requests on CPU before pod is forcibly terminated
      terminationGracePeriodSeconds: 60
---
# Source: teirerank/templates/horizontal-pod-autoscaler.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: teirerank/templates/serviceaccount.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Source: teirerank/templates/servicemonitor.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
