---
# Source: web-retriever/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: web-retriever-config
  labels:
    helm.sh/chart: web-retriever-0.9.0
    app.kubernetes.io/name: web-retriever
    app.kubernetes.io/instance: web-retriever
    app.kubernetes.io/version: "v0.9"
    app.kubernetes.io/managed-by: Helm
data:
  TEI_EMBEDDING_ENDPOINT: "http://web-retriever-tei"
  GOOGLE_API_KEY: ""
  GOOGLE_CSE_ID: ""
  EASYOCR_MODULE_PATH: "/tmp/.EasyOCR"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  HF_HOME: "/tmp/.cache/huggingface"
---
# Source: web-retriever/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: web-retriever
  labels:
    helm.sh/chart: web-retriever-0.9.0
    app.kubernetes.io/name: web-retriever
    app.kubernetes.io/instance: web-retriever
    app.kubernetes.io/version: "v0.9"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7077
      targetPort: 7077
      protocol: TCP
      name: web-retriever
  selector:
    app.kubernetes.io/name: web-retriever
    app.kubernetes.io/instance: web-retriever
---
# Source: web-retriever/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-retriever
  labels:
    helm.sh/chart: web-retriever-0.9.0
    app.kubernetes.io/name: web-retriever
    app.kubernetes.io/instance: web-retriever
    app.kubernetes.io/version: "v0.9"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-retriever
      app.kubernetes.io/instance: web-retriever
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-retriever
        app.kubernetes.io/instance: web-retriever
    spec:
      securityContext:
        {}
      containers:
        - name: web-retriever
          envFrom:
            - configMapRef:
                name: web-retriever-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/web-retriever-chroma:v0.9"
          imagePullPolicy: IfNotPresent
          ports:
            - name: web-retriever
              containerPort: 7077
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: web-retriever
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: web-retriever
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: web-retriever
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {}
      volumes:
        - name: tmp
          emptyDir: {}
