# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-service
  template:
    metadata:
      labels:
        app: router-service
    spec:
      serviceAccountName: default
      containers:
      - name: router-server
        image: opea/gmcrouter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  type: ClusterIP
  selector:
    app: router-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
