# APISIX Namespace
namespace: auth-apisix

# APISIX Helm chart version
apisix:
  version: 2.8.1

# APISIX Helm chart configs
apisix:
  enabled: true
  ingress-controller:
    enabled: true
    config:
      apisix:
        serviceName: auth-apisix-admin
        serviceNamespace: auth-apisix
  etcd:
    replicaCount: 1
    persistence:
      enabled: false
  dashboard:
    enabled: false

